name: servir-training-environment
channels:
  - conda-forge
dependencies:
- numpy
- rasterio
- shapely
- pillow
- geopandas
- scikit-learn
- lightgbm
- matplotlib
- keras
- pip:
  - eo-learn
  - rasterstats
  - treeinterpreter
